services:

  workspace:
    build:
      context: .
    container_name: workspace
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock

    working_dir: /app
    command: sh -c "[ ! -f .env ] && cp .env.example .env; composer install && composer update && npm install && php artisan octane:start --watch --server=swoole --max-requests=250 --host=0.0.0.0 --port=9501"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      sc:
        aliases:
          - workspace


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      sc:
        aliases:
          - postgres


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - postgres
      - workspace
    networks:
      - sc


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9001:9000"
    networks:
      - sc



  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - sc

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "root" ]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - sc

  redis_insight:
    image: redis/redisinsight
    restart: unless-stopped
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - sc


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=root
      - ELASTICSEARCH_PASSWORD=root
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - sc
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - sc
    depends_on:
      - elasticsearch
    volumes:
      - kibana_data:/usr/share/kibana/data

volumes:
  postgres_data:
    name: postgres_data
  portainer_data:
    name: portainer_data
  pgadmin_data:
    name: pgadmin_data
  redis_data:
    name: redis_data
  redis_insight_data:
    name: redis_insight_data
  elasticsearch_data:
    name: elasticsearch_data
  kibana_data:
    name: kibana_data

networks:
  sc:
    name: sc
    driver: bridge
