services:

  workspace:
    build:
      context: .
    container_name: workspace
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "composer install && composer update && tail -f /dev/null"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./log/nginx:/var/log/nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - workspace




volumes:
  postgres_data:
    name: postgres_data
